### ISSUE TITLE
YAML processor: util_yaml.py

### ISSUE THREAD

**Issue by rdoddanavar** [rdoddanavar/hpr-sim#6]
Extend YAML capabilities:
 - Internal references: `ref( ... )`
 - Arithmetic expressions: `eval( ... )` or `expr( ... )`

**Comment by rdoddanavar** [comment]
Changes:
 - Arithmetic expressions don't require keyword
 - Implied evaluation
 - All literal quotes `"..."` removed from YAML fields

**Comment by rdoddanavar** [comment]
Generalize to arbitrary YAML depth using recursion: https://stackoverflow.com/questions/22162321/search-for-a-value-in-a-nested-dictionary-python

**Comment by rdoddanavar** [comment]
```
hello:
    group:
        a:
            value: ref(b.value)
        b:
            value: ref(c)
            max: ref(value)
        c: 1+2
```

 - When depths are asymmetric, references fail Trying to call `hello.group.a.c` --> not an actual field
 - Find way to make `hello.group.c` target instead
