### ISSUE TITLE
Allow math, references in random distribution parameters

### ISSUE THREAD

**Issue by rdoddanavar** [rdoddanavar/hpr-sim#85]
Current implementation of YAML input file parser (`util_yaml.process()`) does not allow for math expressions or internal references in parameter list when specifying random distribution.

For example, this is currently not possible:
```
mass:
    massBody:
        value: 5.0
        unit: lbm
        dist:
            name: normal
            param: [ref(mass.massBody.value), 0.1*ref(mass.massBody.value)]
```

Instead, the user would be forced to hardcode these values to achieve the desired effect:
```
mass:
    massBody:
        value: 5.0
        unit: lbm
        dist:
            name: normal
            param: [5.0, 0.5]
```
